namespace:
  name: sandbox
 
service:
  port: 4111
  protocol: TCP
  type: ClusterIP
  targetPort: 3111

image:
  repository: kayaerol84/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbePath: /healthz
readinessProbePath: /healthz