namespace:
  name: prod

service:
  port: 7111
  protocol: TCP
  type: ClusterIP
  targetPort: 3111

image:
  repository: techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

containerPort: 3111

livenessProbePath: /healthz
readinessProbePath: /healthz